import Navbar from 'componentes/Navbar';
import Rodape from 'componentes/Footer';
import React, { useState } from 'react';
import style from './Dashboard.module.scss';
import Menu from 'componentes/Menu';

const Dashboard: React.FC = () => {
    const [visivel, setVisibel] = useState(false);
    const toggleMenu = (e: any) => {
        setVisibel(!visivel);
        e.stopPropagation();
    }

    const estilos = [
        style.DashboardStyle,
        (!visivel) ? style.hide : style.show
    ];

    return (
        <>
        <Menu visivel={visivel} onClick={toggleMenu} />
        <article className={estilos.join(' ')}>
            <Navbar onClick={toggleMenu} />
            <main>
                <article>
                    <header>DASHBOARD</header>
                    <div id={style.content}>
                        <table>
                            <thead>
                                <tr>
                                    <th>item1</th>
                                    <th>item2</th>
                                    <th>item3</th>
                                    <th>item4</th>
                                    <th>item5</th>
                                    <th>item6</th>
                                    <th>item7</th>
                                    <th>item8</th>
                                    <th>item9</th>
                                    <th>item10</th>
                                    <th>item11</th>
                                    <th>item12</th>
                                    <th>item13</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>  
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr>
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                                <tr>
                                    <td>info1</td>
                                    <td>info2</td>
                                    <td>info3</td>
                                    <td>info4</td>
                                    <td>info5</td>
                                    <td>info6</td>
                                    <td>info7</td>
                                    <td>info8</td>
                                    <td>info9</td>
                                    <td>info10</td>
                                    <td>info11</td>
                                    <td>info12</td>
                                    <td>info13</td>
                                </tr> 
                            </tbody>
                        </table>
                    </div>
                    
                </article>
            </main>
            <Rodape />
        </article> 
        </>
    );
}

export default Dashboard;
